// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Certificate struct {
	ID           int32
	Walletid     pgtype.Int4
	Credentialid pgtype.Text
	Issuedate    pgtype.Date
}

type Wallet struct {
	ID    int32
	Did   string
	Email string
}
